version: "3.8" # Use the version that supports BuildKit syntax

services:
   web:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "3002:3002"
      restart: always
